mywebsite/urls.py
from django.contrib import admin
from penjadwalan import views
from django.urls import path,include


urlpatterns = [
    # admin
    path('login_success', views.login_success, name='login_success'),
    # path('index', views.index_coba, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('login/', views.page_login, name='page_login'),
    path('data/', include('penjadwalan.urls')),
    path('adm', views.index, name = 'index'),
    path('', views.index, name = 'index'),

    path('data_tables', views.data_tables, name='data_tables'),
    path('base', views.base, name='base'),
    path('user/',include('userweb.urls', namespace='generalweb')),
    # path('',include('userweb.urls', namespace='generalweb')),

    # sign up account
    path('signup', views.signup, name='signup'),
    path('signup-siswa', views.signup_siswa, name='signup_siswa'),


]
 


 # path('delete_guru/(?P<id_delete>[0-9])', views.delete_guru, name='delete_guru' ),
 # path('tambah_guru', views.tambah_guru, name='tambah_guru'), 
 # path('data_guru', views.data_guru, name='data_guru'),

userweb/urls.py
from django.urls import path, include
from userweb import views

app_name = 'userweb'
urlpatterns = [
    path('', views.index, name='index'),
    path('base', views.base, name='base'),
    path('kirim_surat_ijin', views.kirim_surat_ijin, name='kirim_surat_ijin'),
    path('user_pengumuman/', views.user_pengumuman, name='user_pengumuman'),
    #jadwal
    path('jadwal/', views.kelas_dropdown, name='data_jadwal'),
    path('jadwal/<int:kelas_id>', views.semuaJadwal, name='jadwal'),

]

userweb/models.py
from django.db import models
from django.contrib.auth.models import User
from penjadwalan.models import *
# Create your models here.

# class StudentAccount(models.Model):
#     user        = models.OneToOneField(User, on_delete=models.CASCADE)
#     nik         = models.CharField(max_length=25)
#     first_name  = models.CharField(max_length=25)
#     last_name   = models.CharField(max_length=25)
#     kelas       = models.ForeignKey(Kelas, on_delete=models.CASCADE)

#     def __str__(self):
#         return '{} {}'.format(self.nik, self.first_name)

# class TeacherAccount(models.Model):
#     user        = models.OneToOneField(User, on_delete=models.CASCADE)
#     guru        = models.ForeignKey(Guru, max_length=25, on_delete=models.CASCADE)

#     def __str__(self):
#         return '{}'.format(self.guru)

userweb/forms.py
from django import forms
from django.forms import ModelForm, CharField
from penjadwalan.models import *

class Fsuratijin(forms.ModelForm):
    class Meta:
        model   = Surat_ijin
        fields  = [
                    'judul',
                    'isi', 
                    'tgl_post',
                    'dokumen',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tgl_post'].widget.attrs.update({'readonly':'disabled'})

userweb/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from penjadwalan.models import *
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Count

# Create your views here.

def group_required(*group_names):
    """Requires user membership in at least one of the groups passed in."""
    
    def in_group(u):
        return u.is_active and (u.is_superuser or bool(u.groups.filter(name__in=group_names)))
    return user_passes_test(in_group)
    
@group_required('students', 'teachers')
def index(request):
    
    # memunculkan context jumlah jam ajar pada guru
    for i in Guru.objects.filter(user=request.user):
        if i.user == request.user:
            idguru_login = i.id
            # print(i.id)
            list_mapel = Penjadwalan.objects.filter(guru=idguru_login)
            jam_ajar = len(list_mapel)

            context= {
                        "jam_ajar" :  "Total {} jam ajar".format(jam_ajar),
            }  
    
            return render(request, 'userweb/index.html', context)
    return render(request, 'userweb/index.html')


@login_required
def user_pengumuman(request):
    for i in User.objects.filter(groups=1):
        if i == request.user:
            mpengumuman = Pengumuman.objects.filter(penerima=2)
        else:
            mpengumuman = Pengumuman.objects.filter(penerima=1)

    context = {
                    "data"  : mpengumuman,
                    "title" : "Pengumuman",
        }
    return render(request, 'userweb/user_pengumuman.html', context)

@login_required
def kirim_surat_ijin(request):
    data_pengirim = User.objects.get(username=request.user)
    print("print user:", data_pengirim.username) #guru2
    add_form = Fsuratijin(request.POST or None)
    # data = {
    #     'pengirim' : data_pengirim,
    # }

    # add_form = Fsuratijin(request.POST or None, initial=data, instance=data_pengirim)

    if request.method == 'POST':
        if add_form.is_valid():
            pengirim    = data_pengirim.username
            judul       = add_form.cleaned_data['judul']
            isi         = add_form.cleaned_data['isi'] 
            tgl_post    = add_form.cleaned_data['tgl_post']
            dokumen     = add_form.cleaned_data['dokumen']
            add_form   = Surat_ijin(pengirim=pengirim, judul=judul, isi=isi, tgl_post=tgl_post, dokumen=dokumen)

            add_form.save()
            print ("INPUT !!!!")
        return redirect('userweb:kirim_surat_ijin')
    
    context = {
        'add_form'  : add_form,
        "title"     : "Kirim Surat Ijin",
    }
    return render(request, 'userweb/kirim_surat_ijin.html', context)


# def user_pengumuman(request,i):
#     mpengumuman = Pengumuman.objects.filter(penerima=i)
#     def in_group(u):
#         if u.groups__name == "students" :
#             i=1
#         else:
#             i=2
#     print(user)
#     context = {
#                 'grup'  : i,
#                 "data"  : mpengumuman,
#                 "title" : "Pengumuman",
#     }
#     return render(request, 'userweb/user_pengumuman.html', context)
    
def base(request):
    return render(request, 'userweb/base.html')


########## jadwal ############
@login_required
def kelas_dropdown(request):
    # kelas_id = request.GET.get('kelas')
    mkelas = Kelas.objects.all().order_by('kelas')
    print(mkelas)
    context = {
                "data" : mkelas,
                }
    template = 'userweb/user_lihat_jadwal.html'
    return render (request, template, context)    

@login_required
def semuaJadwal(request,kelas_id):
 
    hari = [1, 2, 3, 4, 5, 6]
    jam = [1, 2, 3, 4, 5, 6, 7, 8]
    kelas = Kelas.objects.all().order_by('kelas')
    kelas_saat_ini = Kelas.objects.filter(id = kelas_id)
    jadwal = Penjadwalan.objects.filter(kelas = kelas_id)
    list_jadwal = []
    for i in jam:
        for x in hari:
            jadwalku = jadwal.filter(jamke=i,hari=x)
            if jadwalku:
                for y in jadwalku:
                    if y.hari == 1:
                        if y.jamke == i:
                            mapel_senin = y.mapel
                        else:
                            mapel_senin = '-'
                    if y.hari == 2:
                        if y.jamke == i:
                            mapel_selasa = y.mapel
                        else:
                            mapel_selasa = '-'
                    if y.hari == 3:
                        if y.jamke == i:
                            mapel_rabu = y.mapel
                        else:
                            mapel_rabu = '-'
                    if y.hari == 4:
                        if y.jamke == i:
                            mapel_kamis = y.mapel
                        else:
                            mapel_kamis = '-'
                    if y.hari == 5:
                        if y.jamke == i:
                            mapel_jumat = y.mapel
                        else:
                            mapel_jumat = '-'
                    if y.hari == 6:
                        if y.jamke == i:
                            mapel_sabtu = y.mapel
                        else:
                            mapel_sabtu = '-'
            else:
                if x == 1:
                    mapel_senin = '-'
                if x == 2:
                    mapel_selasa = '-'
                if x == 3:
                    mapel_rabu = '-'
                if x == 4:
                    mapel_kamis = '-'
                if x == 5: 
                    mapel_jumat = '-'
                if x == 6:
                    mapel_sabtu = '-'
    # url = request.build_absolute_uri
    # split_url = url.split("/")[-3:]
    # list_url = []
    # for i in split_url:
    #     list_url = list_url.append(i)
    #     return list_url

        list_jadwal.append({
            "mapel_senin"   : mapel_senin,
            "mapel_selasa"  : mapel_selasa,
            "mapel_rabu"    : mapel_rabu,
            "mapel_kamis"   : mapel_kamis,
            "mapel_jumat"   : mapel_jumat,
            "mapel_sabtu"   : mapel_sabtu,
            "kelas"         : kelas_id,
      
            

        })
    # print(list_jadwal)
    
    context = {
        "senin"     : mapel_senin,
        "selasa"    : mapel_selasa, 
        "rabu"      : mapel_rabu,
        "kamis"     : mapel_kamis,
        "jumat"     : mapel_jumat,
        "sabtu"     : mapel_sabtu,
        "jadwal"    : list_jadwal,
        "data"      : kelas,
        "kelas_saat_ini" : kelas_saat_ini, 
        "title"     : "Jadwal Pelajaran"
    }
    
    template = 'userweb/user_lihat_jadwal.html'
    return render (request, template, context)

userweb/templates/userweb/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="icon" href="{% static 'userweb/img/favicon.png' %}" type="image/png" />
    <title>Halaman Akun {{user}}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'userweb/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'userweb/css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/vendors/nice-select/css/nice-select.css' %}" />

    <!-- Data Tables -->
    <link rel="stylesheet" type="text/css" href="{% static 'DataTables/css/datatables.min.css' %}"/> 
    <script type="text/javascript" src="{% static 'DataTables/js/datatables.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'DataTables/images/sort_both.png' %}"/> 
    <link rel="stylesheet" href="{% static 'DataTables/images/sort_asc.png' %}"/> 

    <!-- main css -->
    <link rel="stylesheet" href="{% static 'userweb/css/style.css' %}" />
    <style>
      #logout {
        color: red;
      }
    </style>
  </head>

  <body>
    <!--================ Start Header Menu Area =================-->
    <header class="header_area white-header">
      <div class="main_menu">
        <div class="search_input" id="search_input_box">
          <div class="container">
            <form class="d-flex justify-content-between" method="" action="">
              <input
                type="text"
                class="form-control"
                id="search_input"
                placeholder="Search Here"
              />
              <button type="submit" class="btn"></button>
              <span
                class="ti-close"
                id="close_search"
                title="Close Search"
              ></span>
            </form>
          </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand" href="index.html">
              <img class="logo-2" src="img/logo2.png" alt="" />
            </a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="icon-bar"></span> <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset"
              id="navbarSupportedContent"
            >
              <ul class="nav navbar-nav menu_nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'userweb:index' %}">Home</a>
                </li>
                
                <li class="nav-item submenu ">
                  <a
                    href="{% url 'generalweb:user_pengumuman' %}"
                    class="nav-link"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >Pengumuman</a>
                 
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'userweb:kirim_surat_ijin' %}">Kirim Surat Ijin</a>
                </li>
                <li class="nav-item">
                </li>
                <li class="nav-item submenu dropdown">
                  <a
                    href="#"
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >Hai, {{user}}      <i class="fa fa-caret-down"></i></a>
              
              
                  <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}" id="logout">Keluar</a>
                    </li>
                    
                  </ul>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!--================ End Header Menu Area =================-->

    <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="overlay"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-6">
              <div class="banner_content text-center">
                <h2>{{ title }}</h2>
                <!-- <div class="page_link">
                  <a href="index.html">Home</a>
                  <a href="blog.html">Blog</a>
                  <a href="single-blog.html">Blog Details</a>
                </div> -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Blog Area =================-->
    {% block isi%}
    {% endblock isi%}
    <!--================Blog Area =================-->

    <!--================ Start footer Area  =================-->
    <footer class="footer-area section_gap">
     </footer>
          <!--================ End footer Area  =================-->
      
          <!-- Optional JavaScript -->
          <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="{% static 'userweb/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'userweb/js/popper.js' %}"></script>
    <script src="{% static 'userweb/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'userweb/vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'userweb/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'userweb/js/owl-carousel-thumb.min.js' %}"></script>
    <script src="{% static 'userweb/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'userweb/js/mail-script.js' %}"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="{% static 'userweb/js/gmaps.min.js' %}"></script>
    <script src="{% static 'userweb/js/theme.js' %}"></script>
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>


    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>        
    <script>
    <script>
      $(document).ready( function () {
            $('#senin').DataTable(
                {
                   dom: 'B<"clear">lfrtip',
                   buttons: {
                            name: 'primary',
                            buttons: ['excel', 'pdf', 'print']
                    } }
            );
            $('#selasa').DataTable();
            $('#rabu').DataTable();
            $('#kamis').DataTable();
            $('#jumat').DataTable();
            $('#sabtu').DataTable();
            $('#guru').DataTable();
            $('#ruang').DataTable();
            $('#jampel').DataTable();
            $('#mapel').DataTable();

        } );
  </script>
  </body>
</html>

userweb/templates/userweb/base_guru.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="icon" href="{% static 'userweb/img/favicon.png' %}" type="image/png" />
    <title>Halaman Akun {{user}}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'userweb/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'userweb/css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/vendors/nice-select/css/nice-select.css' %}" />
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'userweb/css/style.css' %}" />
    <style>
      #logout {
        color: red;
      }
    </style>
  </head>

  <body>
    <!--================ Start Header Menu Area =================-->
    <header class="header_area white-header">
      <div class="main_menu">
        <div class="search_input" id="search_input_box">
          <div class="container">
            <form class="d-flex justify-content-between" method="" action="">
              <input
                type="text"
                class="form-control"
                id="search_input"
                placeholder="Search Here"
              />
              <button type="submit" class="btn"></button>
              <span
                class="ti-close"
                id="close_search"
                title="Close Search"
              ></span>
            </form>
          </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand" href="index.html">
              <img class="logo-2" src="img/logo2.png" alt="" />
            </a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="icon-bar"></span> <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset"
              id="navbarSupportedContent"
            >
              <ul class="nav navbar-nav menu_nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'userweb:index' %}">Home</a>
                </li>
                
                <li class="nav-item submenu active">
                  <a
                    href="#"
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >Pengumuman</a
                  >
                  <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a class="nav-link" href="blog.html">Blog</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="single-blog.html"
                        >Blog Details</a
                      >
                    </li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="contact.html">Kirim Surat Ijin</a>
                </li>
                <li class="nav-item">
                </li>
                <li class="nav-item submenu dropdown">
                  <a
                    href="#"
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >Hai, {{user}}      <i class="fa fa-caret-down"></i></a>
              
              
                  <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}" id="logout">Keluar</a>
                    </li>
                    
                  </ul>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!--================ End Header Menu Area =================-->

    <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="overlay"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-6">
              <div class="banner_content text-center">
                <h2>{{ title }}</h2>
                <div class="page_link">
                  <a href="index.html">Home</a>
                  <a href="blog.html">Blog</a>
                  <a href="single-blog.html">Blog Details</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Blog Area =================-->
    {% block pengumuman %}
    {% endblock pengumuman %}
    <!--================Blog Area =================-->

    <!--================ Start footer Area  =================-->
    <footer class="footer-control">
     </footer>
          <!--================ End footer Area  =================-->
      
          <!-- Optional JavaScript -->
          <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="{% static 'userweb/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'userweb/js/popper.js' %}"></script>
    <script src="{% static 'userweb/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'userweb/vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'userweb/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'userweb/js/owl-carousel-thumb.min.js' %}"></script>
    <script src="{% static 'userweb/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'userweb/js/mail-script.js' %}"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="{% static 'userweb/js/gmaps.min.js' %}"></script>
    <script src="{% static 'userweb/js/theme.js' %}"></script>
  </body>
</html>

userweb/templates/userweb/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="icon" href="{% static 'userweb/img/favicon.png' %}" type="image/png" />
    <title>Halaman Akun {{user}}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'userweb/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'userweb/css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'userweb/vendors/nice-select/css/nice-select.css' %}" />
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'userweb/css/style.css' %}" />
    <style>
      #logout {
        color: red;
      }
    </style>
  </head>

  <body>
    <!--================ Start Header Menu Area =================-->
    
    <header class="header_area">
      <div class="main_menu">
        <div class="search_input" id="search_input_box">
          <div class="container">
            <form class="d-flex justify-content-between" method="" action="">
              <input
                type="text"
                class="form-control"
                id="search_input"
                placeholder="Search Here"
              />
              <button type="submit" class="btn"></button>
              <span
                class="ti-close"
                id="close_search"
                title="Close Search"
              ></span>
            </form>
          </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-inverse">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand logo_h" href=""
              ><img width="100" height="100" src="{% static 'images/mimpkkartasura.png' %}" alt=""
            /></a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="icon-bar"></span> <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset"
              id="navbarSupportedContent"
            >
              <ul class="nav navbar-nav menu_nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="index.html">Home</a>
                </li>
    
                <li class="nav-item submenu ">
                  <a
                    href="{% url 'generalweb:user_pengumuman' %}"
                    class="nav-link"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >Pengumuman</a>
                 
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'userweb:kirim_surat_ijin' %}">Kirim Surat Ijin</a>
                </li>
                <!-- <li class="nav-item">
                  <a href="#" class="nav-link search" id="search">
                    <i class="ti-search"></i>
                  </a>
                </li> -->
                <li class="nav-item">
                </li>
                <li class="nav-item submenu dropdown">
                  <a
                    href="#"
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >Hai, {{user}}      <i class="fa fa-caret-down"></i></a>
              
              
                  <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a class="nav-link" >{{jam_ajar}}</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}" id="logout">Keluar</a>
                    </li>
                    
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!--================ End Header Menu Area =================-->

    <!--================ Start Home Banner Area =================-->
    <section class="home_banner_area">
      <div class="banner_inner">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="banner_content text-center">
                <p class="text-uppercase">
                  Selamat Datang di Sistem Informasi Akademik
                </p>
                <h2 class="text-uppercase mt-4 mb-5">
                  MIM PK KARTASURA
                </h2>
                <div>
                  <!-- <a href="#" class="primary-btn2 ml-sm-3 ml-0">Data Diri Siswa</a> -->
                  <a href="{% url 'userweb:data_jadwal' %}" class="primary-btn2 ml-sm-3 ml-0">Jadwal Sekolah</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================ End Home Banner Area =================-->

    <!--================ Start Feature Area =================-->
   
    <!--================ End footer Area  =================-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'userweb/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'userweb/js/popper.js' %}"></script>
    <script src="{% static 'userweb/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'userweb/vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'userweb/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'userweb/js/owl-carousel-thumb.min.js' %}"></script>
    <script src="{% static 'userweb/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'userweb/js/mail-script.js' %}"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="{% static 'userweb/js/gmaps.min.js' %}"></script>
    <script src="{% static 'userweb/js/theme.js' %}"></script>
  </body>
</html>