mywebsite/urls.py
from django.contrib import admin
from penjadwalan import views
from django.urls import path,include


urlpatterns = [
    # admin
    path('login_success', views.login_success, name='login_success'),
    # path('index', views.index_coba, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('login/', views.page_login, name='page_login'),
    path('data/', include('penjadwalan.urls')),
    path('adm', views.index, name = 'index'),
    path('', views.index, name = 'index'),

    path('data_tables', views.data_tables, name='data_tables'),
    path('base', views.base, name='base'),
    path('user/',include('userweb.urls', namespace='generalweb')),
    # path('',include('userweb.urls', namespace='generalweb')),

    # sign up account
    path('signup', views.signup, name='signup'),
    path('signup-siswa', views.signup_siswa, name='signup_siswa'),


]
 


 # path('delete_guru/(?P<id_delete>[0-9])', views.delete_guru, name='delete_guru' ),
 # path('tambah_guru', views.tambah_guru, name='tambah_guru'), 
 # path('data_guru', views.data_guru, name='data_guru'),

penjadwalan/urls.py
from django.contrib import admin
from . import views
from django.urls import path 


urlpatterns = [

    path('', views.data_guru, name='index'),
    
    # lain-lain 
    path('data_surat_ijin', views.data_surat_ijin, name='data_surat_ijin'),
    path('delete_surat_ijin/(^?P<id_delete>[0-9])', views.delete_surat_ijin, name='delete_surat_ijin' ),

    # path('update-surat-ijin', views.data_surat_ijin, name='data_surat_ijin'),
    path('data_pengumuman', views.data_pengumuman, name='data_pengumuman'),
    path('tambah_pengumuman', views.tambah_pengumuman, name='tambah_pengumuman'),
    path('update_pengumuman/<int:id_update>', views.update_pengumuman, name='update_pengumuman'),
    path('delete_pengumuman/(^?P<id_delete>[0-9])', views.delete_pengumuman, name='delete_pengumuman' ),


    # siswa
    path('data_siswa/', views.data_siswa, name='data_siswa'),
    path('siswa_selected_kelas/<int:kelas_id>', views.siswa_selected_kelas, name='siswa_selected_kelas' ),
    path('update_siswa/<int:id_update>', views.update_siswa, name='update_siswa'),
    path('delete_siswa/(^?P<username>)', views.delete_siswa, name='delete_siswa' ),


    # guru
    path('data_guru', views.data_guru, name='data_guru'),
    path('delete_guru/(^?P<username>)', views.delete_guru, name='delete_guru' ),
    path('jml_pel/<int:id_guru>', views.jml_pel, name='jml_pel'),
    path('update_guru/<int:id_update>', views.update_guru, name='update_guru'),
    path('tambah_guru', views.tambah_guru, name='tambah_guru'),
    # mapel
    path('data_mapel', views.data_mapel, name='data_mapel'),
    path('update_mapel/<int:id_update>', views.update_mapel, name='update_mapel'),
    path('tambah_mapel', views.tambah_mapel, name='tambah_mapel'),
    path('delete_mapel/(^?P<id_delete>[0-9])', views.delete_mapel, name='delete_mapel' ),
    # ruang kelas
    path('data_kelas', views.data_kelas, name='data_kelas'),
    path('tambah_kelas', views.tambah_kelas, name='tambah_kelas'),
    path('delete_kelas/(^?P<id_delete>[0-9])', views.delete_kelas, name='delete_kelas' ),
    path('update_kelas/<int:id_update>', views.update_kelas, name='update_kelas'),
    # jam pelajaran
    path('data_jampel', views.data_jampel, name='data_jampel'),
    path('tambah_jampel', views.tambah_jampel, name='tambah_jampel'),
    path('delete_jampel/(^?P<id_delete>[0-9])', views.delete_jampel, name='delete_jampel' ),
    path('update_jampel/<int:id_update>', views.update_jampel, name='update_jampel'),
    # JADWAL
    path('jadwal/', views.kelas_dropdown, name='data_jadwal'),
    path('jadwal/<int:kelas_id>', views.semuaJadwal, name='jadwal'),
    path('update_jadwal/<int:kelas>/<int:hari>/<int:jamke>', views.update_jadwal, name='update_jadwal'),
    path('tambah_jadwal/<int:kelas>/<int:hari>/<int:jamke>', views.tambah_jadwal, name='tambah_jadwal'),
    path('tambah_jadwal2', views.tambah_jadwal2, name='tambah_jadwal2'),
    path('delete_jadwal/(^?P<id_delete>[0-9])', views.delete_jadwal, name='delete_jadwal' ),
]
 
 

userweb/urls.py
from django.urls import path, include
from userweb import views

app_name = 'userweb'
urlpatterns = [
    path('', views.index, name='index'),
    path('base', views.base, name='base'),
    path('kirim_surat_ijin', views.kirim_surat_ijin, name='kirim_surat_ijin'),
    path('user_pengumuman/', views.user_pengumuman, name='user_pengumuman'),
    #jadwal
    path('jadwal/', views.kelas_dropdown, name='data_jadwal'),
    path('jadwal/<int:kelas_id>', views.semuaJadwal, name='jadwal'),

]

penjadwalan/forms.py
from django import forms
from .models import *

class Fpengumuman(forms.ModelForm):
    class Meta:
        model   = Pengumuman
        fields  = [ 'penerima',
                    'judul',
                    'isi',
                    'tgl_post',
                    'dokumen'
        ]
class Ftambahsiswa2(forms.ModelForm):        
    class Meta:
        model   = Siswa
        fields  = [
                    'user',
                    'nis',
                    'nama',
                    'nama_blkg',
                    'kelas',
                  ]   
                  
class Ftambahsiswa(forms.ModelForm):        
    class Meta:
        model   = Siswa
        fields  = [
                    'nis',
                    'nama',
                    'nama_blkg',
                    'kelas',
                  ]   
class Ftambahguru2(forms.ModelForm):        
    class Meta:
        model   = Guru
        fields  = [
                   'user',
                   'nik',
                   'kode',
                   'nama',
                   'nama_blkg', 
                   'gelar',
                  ]     
 
class Ftambahguru(forms.ModelForm):        
    class Meta:
        model   = Guru
        fields  = [
                   'nik',
                   'kode',
                   'nama',
                   'nama_blkg', 
                   'gelar',
                  ]     

class Ftambahmapel(forms.ModelForm):        
    class Meta:
        model   = Mapel
        fields  = [
                  'nama',
                  'kode_mapel',
                  ]
        # labels  = {
		# 	'sksFk':'Jumlah SKS',
		# }

class Ftambahkelas(forms.ModelForm):
    class Meta:
        model   = Kelas
        fields  = [
                  'kode_kelas',
                  'kelas',
                  'kapasitas',
                  'keterangan',
                  ]

class Ftambahjadwal(forms.ModelForm):
    class Meta:
        model   = Penjadwalan
        fields  = [
                    'kode_jadwal', 
                    'kelas',       
                    'hari',       
                    'jamke' ,      
                    'guru',       
                    'mapel',       
                  ]

class Ftambahjadwal2(forms.ModelForm):
    class Meta:
        model   = Penjadwalan
        fields  = [
                    'kode_jadwal', 
                    'kelas',       
                    'hari',       
                    'jamke',      
                    'guru',       
                    'mapel',       
                  ]
 
class LoginForm(forms.Form):
   user = forms.CharField(max_length = 100)
   password = forms.CharField(widget = forms.PasswordInput())

penjadwalan/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
from django.contrib import messages 
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Count
# Create your views here.


############ lain-lain #############
def data_surat_ijin(request):

    msuratijin = Surat_ijin.objects.all()
    

    context={"data"     :  msuratijin, 
            "title"     : "Surat Ijin",
            }
    return render(request, 'penjadwalan/surat_ijin.html', context)

def delete_surat_ijin(request, id_delete):
    Surat_ijin.objects.filter(id=id_delete).delete()
    return redirect('data_surat_ijin')


def data_pengumuman(request):
    mpengumuman = Pengumuman.objects.all()

    context={"data"     :  mpengumuman, 
            "title"     : "Pengumuman",
            }
    return render(request, 'penjadwalan/pengumuman.html', context)

def delete_pengumuman(request, id_delete):
    Pengumuman.objects.filter(id=id_delete).delete()
    return redirect('data_pengumuman')

def tambah_pengumuman(request):
    add_form = Fpengumuman(request.POST or None)
    if request.method == 'POST':
    
        if add_form.is_valid():
           add_form.save()
           print ("INPUT !!!!")

        return redirect('data_pengumuman')
    context = {
        'add_form': add_form,
    }
    return render(request, 'penjadwalan/tambah_pengumuman.html', context )

def update_pengumuman(request, id_update):
    pengumuman_update = Pengumuman.objects.get(id=id_update)
    data = {
        'judul'         : pengumuman_update.judul,
        'isi'           : pengumuman_update.isi,
        'tgl_post'      : pengumuman_update.tgl_post,
    }
    add_form = Fpengumuman(request.POST or None, initial=data, instance=pengumuman_update)
    
    if request.method == 'POST':
        if add_form.is_valid():
           add_form.save()
           print ("save!!!!")
        else:
            print (add_form.errors)

        return redirect('data_pengumuman')
 
    context = {
        'add_form': add_form, 
    }
    return render(request, 'penjadwalan/tambah_pengumuman.html', context )



############ sign up user #############

def signup_siswa(request):
    if request.method == 'POST':
        userform = UserCreationForm(request.POST)
        siswaform = Ftambahsiswa(request.POST or None)

        if userform.is_valid():
            print("tersave")
            userform.save()
            print("tersave2")

            username = userform.cleaned_data.get('username')
            siswa_userform = User.objects.get(username = username)
            # raw_password = userform.cleaned_data.get('password1')
            
            if request.method == "POST" and siswaform.is_valid():
                print("valid guruform")
                # print('tes', guru_userform.id)
                # guruform.user = guru_userform.id
                user_id     = siswa_userform.id
                nis         = siswaform.cleaned_data['nis']
                nama        = siswaform.cleaned_data['nama'] 
                nama_blkg   = siswaform.cleaned_data['nama_blkg']
                kelas       = siswaform.cleaned_data['kelas']
                my_group = Group.objects.get(name='students') 
                my_group.user_set.add(user_id)
                
                siswaform   = Siswa(user_id=user_id, nis=nis, nama=nama, nama_blkg=nama_blkg, kelas=kelas)
                # formfinal.save()
                siswaform.save()

                print("data siswa masok")

                user = authenticate(username=username, password=username)
                login(request, user)
                return redirect('data_siswa')

    else:
        userform    = UserCreationForm()
        siswaform   = Ftambahsiswa()
    context = {
            'userform'  : userform,
            'siswaform' : siswaform,

    }
    return render(request, 'registration/signup_siswa.html', context)


def signup(request):
    if request.method == 'POST':
        userform = UserCreationForm(request.POST)
        guruform = Ftambahguru(request.POST or None)

        if userform.is_valid():
            print("tersave")
            userform.save()
            print("tersave2")

            username = userform.cleaned_data.get('username')
            guru_userform = User.objects.get(username = username)
            # raw_password = userform.cleaned_data.get('password1')
            
            if request.method == "POST" and guruform.is_valid():
                print("valid guruform")
                # print('tes', guru_userform.id)
                # guruform.user = guru_userform.id
                user_id     = guru_userform.id
                nik         = guruform.cleaned_data['nik']
                kode        = guruform.cleaned_data['kode'] 
                nama        = guruform.cleaned_data['nama']
                nama_blkg   = guruform.cleaned_data['nama_blkg']
                gelar       = guruform.cleaned_data['gelar']
                my_group = Group.objects.get(name='teachers') 
                my_group.user_set.add(user_id)
                
                guruform   = Guru(user_id=user_id, nik=nik, kode=kode, nama=nama, nama_blkg=nama_blkg, gelar=gelar)
                # formfinal.save()
                guruform.save()

                print("data guru masok")

                user = authenticate(username=username, password=username)
                login(request, user)
                return redirect('data_guru')

    else:
        userform = UserCreationForm()
        guruform = Ftambahguru()
    context = {
            'userform': userform,
            'guruform': guruform,

    }
    return render(request, 'registration/signup.html', context)


def group_required(*group_names):
    """Requires user membership in at least one of the groups passed in."""
    # def in_groups(u):
    #     if u.is_authenticated():
    #         if bool(u.groups.filter(name__in=group_names)):
    #             return True
    #     return False

    # return user_passes_test(in_groups, login_url='403')
    def in_group(u):
        return u.is_active and (u.is_superuser or bool(u.groups.filter(name__in=group_names)))
    return user_passes_test(in_group)
    
@group_required('students', 'teachers')
def login_success(request):
    """
    Redirects users based on whether they are in the admins group
    """
    if request.user.groups.filter(name="students").exists():
        # user is an admin
        print("berhasil masuk index user")
        return redirect("generalweb:index")
    if request.user.groups.filter(name="teachers").exists():
        # user is an admin
        print("berhasil masuk index guru")
        return redirect("generalweb:index")
    else:
        print("masuk admin")
        return redirect("index")

############ base #############
@user_passes_test(lambda u: u.is_superuser)
def base(request):
    return render(request, 'penjadwalan/base.html')
@user_passes_test(lambda u: u.is_superuser)
def index(request):
    return render(request, 'penjadwalan/index.html')

@user_passes_test(lambda u: u.is_superuser)
def data_tables(request):
    return render(request, 'penjadwalan/tables-data.html', context)

############ siswa #############
@user_passes_test(lambda u: u.is_superuser)

def siswa_selected_kelas(request, kelas_id):
    mkelas = Kelas.objects.all().order_by('kelas')
    msiswa = Siswa.objects.filter(kelas = kelas_id)
    kelas_selected = Kelas.objects.filter(id = kelas_id)
    print(msiswa)

    print(mkelas)
    context = {
                "kelas_selected" : kelas_selected,
                "data"  : msiswa,
                "kelas" : mkelas,
                "title" : "Siswa",
                }
    return render (request, "penjadwalan/data_siswa.html", context)

@user_passes_test(lambda u: u.is_superuser)
def data_siswa(request):

    kelas_selected = " "
    mkelas  = Kelas.objects.all().order_by('kelas')
    msiswa = Siswa.objects.all()

    
    context={
            "kelas_selected" : kelas_selected,
            "data"     : msiswa, 
            "kelas"     : mkelas,
            "title"     : "Siswa",
 
            }
    return render(request, 'penjadwalan/data_siswa.html', context)


@user_passes_test(lambda u: u.is_superuser)

def update_siswa(request, id_update):
    siswa_update = Siswa.objects.get(id=id_update)
    data = {
        'user'          : siswa_update.user,
        'nis'           : siswa_update.nis,
        'nama'          : siswa_update.nama,
        'nama_blkg'     : siswa_update.nama_blkg,
        'kelas'         : siswa_update.kelas,
    }
    add_form = Ftambahsiswa2(request.POST or None, initial=data, instance=siswa_update)
    
    if request.method == 'POST':
        if add_form.is_valid():
           add_form.save()
           print ("save!!!!")
        else:
            print (add_form.errors)

        return redirect('data_siswa')
 
    context = {
        'add_form': add_form,
    }
    return render(request, 'penjadwalan/tambah_siswa.html', context )

def delete_siswa(request, username):
    User.objects.filter(username=username).delete()
    return redirect('data_siswa')

############ guru #############
@user_passes_test(lambda u: u.is_superuser)
def data_guru(request):
    
    mguru = Guru.objects.all()
    mjadwal = Penjadwalan.objects.all()
    mapel = Penjadwalan.objects.values('guru').annotate(Count('mapel'))
    # join1 = Penjadwalan.objects.selected_related('guru')
    list_guru=[]
    # print(mapel)
    # for i in mapel:
    #     # print(i.get('guru'))
    #     list_data = []
    #     guru = Guru.objects.filter(id=i.get('guru'))
    #     print('kkkkkkkkkkkk',guru)
    #     for x in guru:
    #         jumlah_jam = i.get('mapel__count')
    #         nama_guru = x.nama
    #         id_guru = x.id

penjadwalan/templates/penjadwalan/data_siswa.html
{% extends 'penjadwalan/base.html' %}
{% load static %}

            {% block judul %}
            {% for x in kelas_selected %}
            <title>Data Siswa Kelas {{x.kelas}}</title>
            {% endfor %}
            {% endblock judul%}

            {% block link %}
               <h1>
                    <a href="{% url 'index' %}">Dashboard</a>
                    / <b> <a href="{% url 'data_siswa' %}">Data Siswa </a>  </b> 

               </h1>             
            {% endblock link %}
           {% block table %} 
            <div class="animated fadeIn">
                <div class="row">

                    <div class="col-md-12">
                        
                            <a href="{% url 'signup_siswa' %}"><button class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Akun dan Data {{ title }}</button>
                        
                        <div class="card"></a>
                      
                        
                            <div class="card-header">
                                <strong class="card-title">Data Siswa</strong> 
                            </div>
                            
                            <div class="card-body">
                                <form method='post' action='' >

                                <select class="btn btn-info dropdown-toggle"  id="pilkelas" name="URL" onchange="window.location.href= this.form.URL.options[this.form.URL.selectedIndex].value">
                                    <option value='' > Lihat Berdasarkan Kelas </option>
                                    {% for i in kelas %}
                                        <option value="{% url 'siswa_selected_kelas' i.id %}">{{i.kelas|upper}} </a></option>
                                    {% endfor %}
                                    <option value="{% url 'data_siswa' %}">Lihat Keseluruhan </a></option>
                                </select>
                            </form>
                                <hr>
                                <table id="senin" class="table table-striped table-bordered" >
                                   
                                    <thead>
                                        
                                        <tr>
                                            
                                            <th>NO</th>
                                            <th>NIS</th>
                                            <th>Nama</th>
                                            <th>Username</th>
                                            <th>Kelas</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>

                                    <!-- {% for x in data %}
                                            {{x.0}}
                                        {%endfor%} -->

                                        
                                    <tbody>
                                        {% for x in data %}
                                        <tr>
                                           
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ x.nis }}</td>
                                            <td>{{ x.nama }} {{ x.nama_blkg }}</td>
                                            <td>{{ x.user }}</td>
                                            <td>{{ x.kelas }}</td>
                                            <td><a href="{% url 'update_siswa' x.id %}"><button class="btn btn-primary"><i class="fa fa-pencil"></i></button></a> 
                                                <a href="{% url 'delete_siswa' x.user %}" class="confirm-delete"><button class="btn btn-danger"><i class="fa fa-trash"></i></button></a></td>
                                        </tr>
                                        {% endfor %}
                       
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div><!-- .animated -->
        {% endblock%}  

   

penjadwalan/templates/penjadwalan/edit_mapel.html
<form>
        <table>
            <tr>
                <td>Mata Pelajaran</td>
                <td><input type="text" name="nama" placeholder="" /></td>
            </tr>
            <tr>
                <td> Kode </td>
                <td><input type="text" name="kode_mapel" placeholder="" /></td>
            </tr>
            <tr>
                <td>Jumlah sks</td>
                <td><input type="text" name="sksFk" placeholder="" /></td>
            </tr>
                    <td></td>
                    <td><button type="submit" name="submit" > Update Data </button></td>
                </tr>
        </table>
    </form>

penjadwalan/templates/penjadwalan/page-register.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sufee Admin - HTML5 Admin Template</title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">


    <link rel="stylesheet" href="vendors/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="vendors/themify-icons/css/themify-icons.css">
    <link rel="stylesheet" href="vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="vendors/selectFX/css/cs-skin-elastic.css">

    <link rel="stylesheet" href="assets/css/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>



</head>

<body class="bg-dark">


    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="index.html">
                        <img class="align-content" src="images/logo.png" alt="">
                    </a>
                </div>
                <div class="login-form">
                    <form>
                        <div class="form-group">
                            <label>User Name</label>
                            <input type="email" class="form-control" placeholder="User Name">
                        </div>
                            <div class="form-group">
                                <label>Email address</label>
                                <input type="email" class="form-control" placeholder="Email">
                        </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" class="form-control" placeholder="Password">
                        </div>
                                    <div class="checkbox">
                                        <label>
                                <input type="checkbox"> Agree the terms and policy
                            </label>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Register</button>
                                    <div class="social-login-content">
                                        <div class="social-button">
                                            <button type="button" class="btn social facebook btn-flat btn-addon mb-3"><i class="ti-facebook"></i>Register with facebook</button>
                                            <button type="button" class="btn social twitter btn-flat btn-addon mt-2"><i class="ti-twitter"></i>Register with twitter</button>
                                        </div>
                                    </div>
                                    <div class="register-link m-t-15 text-center">
                                        <p>Already have account ? <a href="#"> Sign in</a></p>
                                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <script src="vendors/jquery/dist/jquery.min.js"></script>
    <script src="vendors/popper.js/dist/umd/popper.min.js"></script>
    <script src="vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="assets/js/main.js"></script>


</body>

</html>

penjadwalan/templates/penjadwalan/user_lihat_jadwal.html
{% load static %}

            {% block judul %}
            {% for i in kelas_saat_ini %}
            <title>Data Jadwal Kelas {{i.kelas}}</title>
            {% endfor %}
            {% endblock judul%}

   
            {% block link %} 
           
          
               
               <h1>
                    <a href="{% url 'index' %}">Dashboard</a>
                    / <b> <a href="{% url 'data_jadwal' %}">Jadwal </a>  </b> 

               </h1> 
                
            {% endblock link %}
            
           {% block isi %} 
           <br>
           <section>
           
            <div class="bg-primary">
                <h3>Silakan memilih kelas </h3>
                <div class="row">
                    <div class="col-lg-12 ">
                        <div class="single-post row">
                            <div class="col-lg-12">
                               
                            </div>
                            <div class="col-lg-12">
                                   
        
                       
               
                  <div class="card col-md-12"></a>
                    <P>
                 
                        <form method='post' action='' >
                           <select class="btn "  id="pilkelas" name="URL" onchange="window.location.href= this.form.URL.options[this.form.URL.selectedIndex].value">
                               <option value='' >Pilih Kelas</option>
                               {% for i in data %}
                               {{i.kelas|upper}}
                                   <option value="{% url 'userweb:jadwal' i.id %}"> {{i.kelas|upper}} </a></option>
                               {% endfor %}
                           </select>
                       </form>
                     </P>
                     
                    <div class="card-header">
                      {% for i in kelas_saat_ini %}
                        <strong class="card-title">Data Kelas {{ i.kelas|upper }}</strong>
                      {% endfor %}
                      </div>
                    
                    <div class="card-body">
                <table id="senin" class="table table-striped table-bordered" >
                    <thead>
                        <tr>
                                <th>Jam</th>
                                <th>Senin</th>
                                <th>Selasa</th>
                                <th>Rabu</th>
                                <th>Kamis</th>
                                <th>Jumat</th>
                                <th>Sabtu</th>
            
                        </tr>
                    </thead>         
                    <tbody>
                       
                        {% for x in jadwal %}
                        <tr>
                            <td>{{forloop.counter}}</td> 
                            {% if x.mapel_senin == '-' %}
                                </script> 
                                  <td>{{x.mapel_senin}}</a></td> 
                            {% else %}
                                  <td>{{x.mapel_senin}} | {{x.guru}}</a></td> 
                        
                           {% endif %}
                           {% if x.mapel_selasa == '-' %}
                                  <td>{{x.mapel_selasa}}</a></td> 
                            {% else %}
                            <td>{{x.mapel_selasa}}</a></td> 
                           {% endif %}
                         
                            <td>{{x.mapel_rabu}}</td> 
                            <td>{{x.mapel_kamis}}</td> 
                            <td>{{x.mapel_jumat}}</td> 
                            <td>{{x.mapel_sabtu}}</td> 
                        </tr>
                        {% endfor %}                
                    </tbody>
                    
                </table>
                </div>
                </div>
                            </div>
                        </div>
                </div>
            </div>
          
          
          
          
          </section>
         
            

           <!-- END OF FULL TABS -->
            <!-- .animated -->
        {% endblock%}

        {% block js %}
        
        <script>
        function openPage(pageName, elmnt, color) {
            // Hide all elements with class="tabcontent" by default */
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
              tabcontent[i].style.display = "none";
            }
          
            // Remove the background color of all tablinks/buttons
            tablinks = document.getElementsByClassName("tablink");
            for (i = 0; i < tablinks.length; i++) {
              tablinks[i].style.backgroundColor = "";
            }
          
            // Show the specific tab content
            document.getElementById(pageName).style.display = "block";
          
            // Add the specific color to the button used to open the tab content
            elmnt.style.backgroundColor = color;
          }
          
          // Get the element with id="defaultOpen" and click on it
          document.getElementById("defaultOpen").click();
        </script>
        {% endblock js %}


   <!-- LAST -->
 